---

- name: Create ~/.vifm
  file:
    path: "{{ ansible_env.HOME }}/.vifm"
    state: directory

- name: Symlink vifm configs
  file:
      src: "{{ role_path }}/{{ item.path }}"
      dest: "{{ ansible_env.HOME }}/{{ item.name }}"
      state: link
      force: yes
  with_items:
      - {path: "files/vifmrc", name: ".vifm/vifmrc"}
